// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeReorder.Entity;

namespace TreeReorder.Migrations
{
    [DbContext(typeof(NodeContext))]
    partial class NodeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TreeReorder.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime>("ModifiDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.Property<int>("parentId");

                    b.HasKey("Id");

                    b.ToTable("Nodes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Node");
                });

            modelBuilder.Entity("TreeReorder.Models.FileNode", b =>
                {
                    b.HasBaseType("TreeReorder.Models.Node");

                    b.Property<string>("Path");

                    b.Property<long>("Size");

                    b.ToTable("FileNode");

                    b.HasDiscriminator().HasValue("FileNode");
                });

            modelBuilder.Entity("TreeReorder.Models.FolderNode", b =>
                {
                    b.HasBaseType("TreeReorder.Models.Node");


                    b.ToTable("FolderNode");

                    b.HasDiscriminator().HasValue("FolderNode");
                });
#pragma warning restore 612, 618
        }
    }
}
